customhost = "employee.cwaqnyx8uyjt.us-east-2.rds.amazonaws.com"
customuser = "cheelvis"
custompass = "Passw0rd123!"
customdb = "employee"
custombucket = "cf-templates-qo3wxwz9hxw-us-east-2"
customregion = "us-east-2"
